Wallpapers/bunsen-1920x1200.jpg usr/share/backgrounds/Bunsen1
Wallpapers/bunsen2-1920x1200.jpg usr/share/backgrounds/Bunsen1
Wallpapers/bunsen3-1920x1200.jpg usr/share/backgrounds/Bunsen1
Wallpapers/grey.jpg usr/share/backgrounds/Bunsen1
Wallpapers/inksplat-1920x1200.png usr/share/backgrounds/Bunsen1
Wallpapers/joy-1920x1200.png usr/share/backgrounds/Bunsen1
Wallpapers/lines-1920x1200.png usr/share/backgrounds/Bunsen1
Wallpapers/lines-2560x1080.png usr/share/backgrounds/Bunsen1
